trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  proyecto: 'Veterinary.API/Veterinary.API.csproj'

steps:
- checkout: self # Aseg√∫rate de clonar el repositorio

- script: dir D:\a\1\s
  displayName: 'List contents of the working directory' # Verifica el contenido del directorio

- task: UseDotNet@2
  displayName: 'ASP.NET Core 8'
  inputs:
    packageType: 'sdk'
    version: '8.0.403'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'Restore dependencies'
  inputs:
    command: 'restore'
    projects: '$(proyecto)'

- script: dotnet build --configuration $(buildConfiguration) '$(proyecto)' --verbosity detailed
  workingDirectory: D:\a\1\s
  displayName: 'dotnet build $(buildConfiguration)'
